import { useEffect,useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, HeartHandshake, PlayCircle } from 'lucide-react';
const slides=[
  {image:'/images/church-service.jpg',eyebrow:'Awake Grace Ministries International – UK',title:'Come and Encounter Jesus Christ',text:'A Christ-centred church family serving Ashford and Leicester through worship, the Word, prayer, fellowship and community.'},
  {image:'/images/worship-man.jpg',eyebrow:'Worship • Word • Prayer',title:'A Place to Worship, Grow & Belong',text:'Join us every Sunday and throughout the week as we seek God together and build strong communities of faith.'},
  {image:'/images/glory-blue.jpg',eyebrow:'Conferences • Missions • Outreach',title:'Taking Grace Beyond the Church Walls',text:'From the UK to Zambia and Zimbabwe, we serve communities through missions, charity, volunteering and practical care.'},
];
export default function HeroSlider(){const [i,setI]=useState(0);useEffect(()=>{const id=setInterval(()=>setI(v=>(v+1)%slides.length),6500);return()=>clearInterval(id)},[]);return <section className="relative h-[92vh] min-h-[680px] overflow-hidden bg-[#07102b]">{slides.map((s,n)=><img key={s.image} src={s.image} className={`absolute inset-0 w-full h-full object-cover transition-opacity duration-1000 ${n===i?'opacity-100':'opacity-0'}`}/>) }<div className="absolute inset-0 bg-gradient-to-r from-[#040717]/95 via-[#09132b]/75 to-black/25"/><div className="absolute inset-0 bg-gradient-to-t from-[#040717] via-transparent to-black/30"/><div className="relative z-10 max-w-7xl mx-auto px-6 h-full flex items-center"><div className="max-w-3xl pt-16"><span className="inline-flex px-4 py-2 rounded-full border border-sky-300/30 bg-sky-400/10 text-sky-200 text-xs font-bold uppercase tracking-[.2em] mb-6">{slides[i].eyebrow}</span><h1 className="text-white text-5xl md:text-7xl font-black leading-[1.02] mb-6">{slides[i].title}</h1><p className="text-slate-200 text-lg md:text-xl leading-relaxed max-w-2xl mb-9">{slides[i].text}</p><div className="flex flex-wrap gap-3"><Link to="/contact" className="church-btn"><PlayCircle size={18}/> Plan Your Visit</Link><Link to="/give" className="church-btn-alt"><HeartHandshake size={18}/> Give / Donate</Link><Link to="/prayer" className="church-btn-ghost">Request Prayer <ArrowRight size={17}/></Link></div></div></div><div className="absolute bottom-8 left-1/2 -translate-x-1/2 z-20 flex gap-2">{slides.map((_,n)=><button key={n} onClick={()=>setI(n)} className={`h-2 rounded-full transition-all ${n===i?'w-9 bg-amber-300':'w-2 bg-white/40'}`}/>)}</div></section>}
